language: node_js

node_js:
    - 4.6
    - 6.9

notifications:
    email: false

before_install: npm install -g grunt-cli

script:
    - ./node_modules/.bin/travis-commit-message-checker
    - npm test

